### ISSUE TITLE
[EPIC] Create a Flow dApp Scaffold to serve as a template and documentation material

### ISSUE THREAD

**Issue by fotescodev** [onflow/scaffold-flow#2]
Scaffold-flow was inspired by https://github.com/scaffold-eth/scaffold-eth, which is one of the most forked Web3 repositories in the space. 

The problem being solved:

- lack of end-to-end Flow Dapp examples that are easy to follow
- lack of one sample project that can be extensible enough to create multiple use cases by the community

Task List:

- [ ] Copy Blokctalk (former Twitter3) https://github.com/onflow/blocktalk to https://github.com/onflow/scaffold-flow
- [ ] Trim down the scaffold-flow code from the Twitter API calls
- [ ] Update scaffold-flow README and invite the community to contribute ideas
- [ ] Include scaffold-flow into Flow CLI Scaffold list
- [ ] Digest existing Blocktalk Tutorial into a simple version (minus Twitter API)
- [ ] Add scaffold-flow tutorial to the Developer Portal
